# -*- coding: utf-8 -*-
"""senti-bot (final).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17n89Z-8RhLjL5VR5CA6l0Lx5IfUpJJ2a

# SENTI-BOT: A SENTIMENT ANALYSIS CHATBOT
(CODES)

# Installing libraries
"""

#!pip install random
#!pip install textlab

"""# Importing libraries"""

import random
from textblob import TextBlob

"""# building a chatbot [senti-bot]"""

# introduction
name = input("What is your name ?  ")
age = input("what is your age ? ")



# Greeting selection
greetings = ["hello",
             "have a wonderful day",
             "have a good day!  ",
             "hope you had an amazing day!   ",
             "hope you had an awesome day"]



#welcome
print(random.choice(greetings))
print("chatbot: My name is sentibot. If you wish to exit just say no or you can chat with me.  ")
print("i can help you in analysing your sentiment. if you wish to test say 'yes' else say 'no'")
chat=str(input(name))






#questions
questions=["do you have friends ? ",
          "Are you financially independent ? ",
           "Do you have family support?",
           "Are your children happy?"]




#code for chatbot
p = 0
n = 0

if "y" in chat.lower():
  print("welcome to sentiment analysis chatbot !")
  for i in range(0, random.randint(3, 4)):

      q = random.choice(questions)    
      questions.remove(q)
      question = q 
      print(question)
      
      questionsA = input()
      blob = TextBlob(questionsA)
      if "y" in blob.lower():
        positive=[ "oh! that is great...",
            "amazing:)",
            "good to know",
            "wow! that is awesome",
            "superb" ]
        print(random.choice(positive))
        p=p+1
      else:
          negative=["you will soon get tons of happiness",
              "have faith in god everything will be fine",
              "you are not alone! i am there for you",
              "that is awful. but dont forget you have the best smile.",
              "everything happens for a reason.You are one of the bravest people I know"]
          print(random.choice(negative))   
          n=n+1





# Random bye
byes = [
    " bye !",
    "bye! bye!",
    " See you later",
    "nice to meet you!",
    "Good bye!"
]

print(random.choice(byes))




#sentiment analysis
if "y" in chat.lower():
  if p>n:
    print('the sentiment is positive')
  else:
    print('the sentiment is negative')



