# -*- coding: utf-8 -*-
"""tic tac toe

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/110FBXT6FwPLsZsfQlDbnB1fYthETI3yA
"""

print("Hi... I'm an AI Tic-Tac-Toe game. Welcome. Let's play some Tic-Tac-Toe... Let's get started!!!!")
print('''Use the following as reference:-
1 | 2 | 3
---------
4 | 5 | 6
---------
7 | 8 | 9
''')

# Making the grid
board = [" "] * 9


# Check for a win
def check_win(board, player):
    win_conditions = [(0, 1, 2), (3, 4, 5), (6, 7, 8), 
                      (0, 3, 6), (1, 4, 7), (2, 5, 8), 
                      (0, 4, 8), (2, 4, 6)]           
    return any(board[a] == board[b] == board[c] == player for a, b, c in win_conditions)

# Check for a draw
def check_draw(board):
    return " " not in board

# Making a move
def make_move(board, position, player):
    if board[position] == " ":
        board[position] = player
        return True
    return False

# AI making a move
def ai_move(board):
    # Check if AI can win in the next move
    for i in range(9):
        if board[i] == " ":
            board[i] = "O"
            if check_win(board, "O"):
                return
            board[i] = " "

    # Check if player can win in the next move and block them
    for i in range(9):
        if board[i] == " ":
            board[i] = "X"
            if check_win(board, "X"):
                board[i] = "O"
                return
            board[i] = " "

    # If no one can win, pick the first available spot
    for i in range(9):
        if board[i] == " ":
            board[i] = "O"
            return

# Play the game
def play_game():
    print("OK NOW LET THE COUNTDOWN BEGIN\n1...\n2...\n3....GO\n")
    for row in [board[i:i+3] for i in range(0, 9, 3)]:
        print("|".join(row))
        print("-" * 5)

    while True:
        # Human player move
        move = int(input("Enter your move (1-9): ")) - 1
        if make_move(board, move, "X"):
            for row in [board[i:i+3] for i in range(0, 9, 3)]:
                  print("|".join(row))
                  print("-" * 5)
            if check_win(board, "X"):
                print("Congratulations! You win!")
                break
            elif check_draw(board):
                print("It's a draw!")
                break

            # AI move
            ai_move(board)
            print("AI has made its move:")
            for row in [board[i:i+3] for i in range(0, 9, 3)]:
                  print("|".join(row))
                  print("-" * 5)
            if check_win(board, "O"):
                print("AI wins!")
                break
            elif check_draw(board):
                print("It's a draw!")
                break
        else:
            print("Invalid move, try again.")

play_game()



